databases:
  - name: travel-db
    databaseName: travel_app_db
    user: travel_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: alx-travel-app
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python alx_travel_app/manage.py collectstatic --noinput
      python alx_travel_app/manage.py migrate
    startCommand: gunicorn alx_travel_app.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: travel-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "alx-travel-app.onrender.com"

  - type: worker
    name: celery-worker
    env: python
    plan: free
    region: frankfurt
    repo: <GITHUB_REPO_URL>
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_travel_app worker --loglevel=info
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: travel-db
          property: connectionString
      - key: CELERY_BROKER_URL
        sync: false
