databases:
  - name: travel-db
    databaseName: travel_db
    user: travel_user
    plan: free
    region: frankfurt   # or oregon / any region close to you

services:
  - type: web
    name: alx-travel-app
    env: python
    plan: free
    region: frankfurt   # must match database region
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn alx_travel_app.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: travel-db
          property: connectionString

  - type: worker
    name: celery-worker
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A alx_travel_app worker --loglevel=info
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: travel-db
          property: connectionString
      - key: CELERY_BROKER_URL
        sync: false
